# Generated by Django 3.1.4 on 2021-01-03 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('student_name_surname', models.CharField(max_length=30)),
                ('college', models.CharField(default='SOME STRING', max_length=255)),
                ('program', models.CharField(default='SOME STRING', max_length=255)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10)),
                ('slug', models.SlugField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='university.student')),
                ('university_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.university_name')),
            ],
        ),
    ]
