# Generated by Django 3.1.4 on 2021-01-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='name_surname',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
    ]
