# Generated by Django 3.1.4 on 2021-04-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
