# Generated by Django 3.1.4 on 2021-05-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='slug',
        ),
    ]
