# Generated by Django 3.1.4 on 2021-05-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_remove_student_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
